baseURL = 'https://www.medplum.com/'
languageCode = 'en-us'
title = 'Medplum'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github'

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "node_modules/@tabler/icons/icons"
  target = "assets/icons/tabler"

[[module.mounts]]
  source = "node_modules/mermaid/dist"
  target = "assets/js/vendor/mermaid"

[[module.mounts]]
  source = "node_modules/swup/dist"
  target = "assets/js/vendor/swup"
