baseURL = 'https://www.medplum.com/'
languageCode = 'en-us'
title = 'Medplum'

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "node_modules/@tabler/icons/icons"
  target = "assets/icons/tabler"

[[module.mounts]]
  source = "node_modules/mermaid/dist"
  target = "assets/js/vendor/mermaid"

[[module.mounts]]
  source = "node_modules/swup/dist"
  target = "assets/js/vendor/swup"
